# version: "3"

services:

  web:
    build:
      context: ./docker/nginx

    volumes:
      - ./centraldatabasecode:/app:ro

    ports:
      - ${WEB_PORT}:80

    working_dir: /app

  php:
    build:
      context: ./docker/php

      args:
        - PUID=${PUID}
        - PGID=${PGID}

    volumes:
      - ./centraldatabasecode:/app
      # - .:/app
      

    working_dir: /app

    env_file:
      - ./.env

  node:
    image: node:lts-alpine
    
    volumes:
      - ./centraldatabasecode:/app
      # - .:/app
      

    working_dir: /app

    user: ${PUID}:${PGID}

    env_file:
      - ./.env

    tty: true

    ports:
      - ${DEV_PORT}:${DEV_PORT}

  db:
    image: mysql/mysql-server:latest

    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

    volumes:
      - ./data/db_files:/var/lib/mysql